# spring.application.name=auth
# spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_auth
# spring.datasource.username=sa
# spring.datasource.password=Root1234!
# spring.datasource.driver-class-name=org.postgresql.Driver

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_auth
    driver-class-name: org.postgresql.Driver
    username: sa
    password: Root1234!
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
